Repository getting-things-gnome/gtg, pull requests merged in 2021-01, with the labels that each got.

#530 Optim/no refresh on hidden pane
  GTG/gtk/browser/main_window.py
Labels: enhancement, performance, priority:high, reproducible-in-git

#526 Fix task date sorting order in certain situations
  GTG/gtk/browser/treeview_factory.py
Labels: enhancement

#536 Update Spanish translation
  po/es.po
Labels: enhancement

#547 Fixing switch pane optimization
  GTG/gtk/browser/main_window.py
  GTG/gtk/browser/tag_editor.py
Labels: enhancement

#539 Using lazy evaluated string for logging
  GTG/backends/__init__.py
  GTG/backends/generic_backend.py
  GTG/backends/unmaintained/backend_evolution.py
  GTG/backends/unmaintained/backend_launchpad.py
  GTG/backends/unmaintained/backend_mantis.py
  GTG/backends/unmaintained/backend_rtm.py
  GTG/backends/unmaintained/generictomboy.py
  GTG/backends/unmaintained/rtm/rtm.py
  GTG/core/config.py
  GTG/core/datastore.py
  GTG/core/keyring.py
  GTG/core/logger.py
  GTG/core/meson.build
  GTG/core/plugins/api.py
  GTG/core/plugins/engine.py
  GTG/core/requester.py
  GTG/core/task.py
  GTG/core/timer.py
  GTG/core/xml.py
  GTG/gtg.in
  GTG/gtk/application.py
  GTG/gtk/backends/__init__.py
  GTG/gtk/browser/cell_renderer_tags.py
  GTG/gtk/browser/main_window.py
  GTG/gtk/browser/tag_editor.py
  GTG/gtk/browser/treeview_factory.py
  GTG/gtk/editor/editor.py
  GTG/gtk/editor/taskview.py
  GTG/plugins/export/export.py
  GTG/plugins/hamster/hamster.py
  GTG/plugins/untouched_tasks/untouchedTasks.py
  po/POTFILES.in
Labels: enhancement, performance
