Repository getting-things-gnome/gtg, pull requests merged in 2021-04, with the labels that each got.

#610 Fix recurring term not displayed correctly in Editor
  GTG/core/task.py
  GTG/core/xml.py
  GTG/gtk/editor/recurring_menu.py
Labels: Pull Request

#563 Add Collapse and Expand all tasks buttons
  GTG/gtk/browser/main_window.py
  GTG/gtk/data/main_window.ui
Labels: enhancement

#598 debug.sh: Add -p prefix-prog for better control
  scripts/debug.sh
Labels: enhancement

#644 Remove fake update_date when task is not repeating
  GTG/core/xml.py
Labels: Pull Request, priority:low

#623 test parse_only_month_day_for_recurrency method
  tests/tools/test_dates.py
Labels: Pull Request, enhancement

#646 Update Brazilian Portuguese translation
  po/pt_BR.po
Labels: enhancement
