Repository getting-things-gnome/gtg, pull requests merged in 2022-01, with the labels that each got.

#525 Rewriting the CalDAV plug from scratch
  GTG/backends/__init__.py
  GTG/backends/backend_caldav.py
  GTG/backends/backend_localfile.py
  GTG/backends/generic_backend.py
  GTG/backends/meson.build
  GTG/core/dates.py
  GTG/core/keyring.py
  GTG/core/task.py
  GTG/gtk/backends/addpanel.py
  GTG/gtk/backends/backendscombo.py
  GTG/gtk/backends/backendstree.py
  GTG/gtk/backends/configurepanel.py
  GTG/gtk/data/main_window.ui
  README.md
  flatpak/org.gnome.GTG-stable.json
  flatpak/org.gnome.GTG.json
  tests/backend/__init__.py
  tests/backend/backend_caldav_test.py
  tests/test_utils.py
Labels: enhancement, plugins

#749 Don't loop forever with invalid quick add date
  GTG/gtk/browser/quick_add.py
  tests/core/test_quickadd.py
Labels: bug, Pull Request

#754 Prevent errors when no task is selected
  GTG/gtk/application.py
Labels: bug
