Repository getting-things-gnome/gtg, pull requests merged in 2022-04, with the labels that each got.

#869 Correct subtasks formatting in e-mail plugin
  GTG/plugins/send_email/sendEmail.py
Labels: enhancement, plugins

#875 Fix collaborative calendar tags
  GTG/backends/backend_caldav.py
Labels: enhancement, plugins

#871 GTK/gtk/browser/delete_tag.py: Small language improvement
  GTG/gtk/browser/delete_tag.py
Labels: enhancement

#853 Open tag panel by default
  GTG/core/config.py
Labels: enhancement

#856 Keep modified date when reading from file
  GTG/core/xml.py
Labels: bug, enhancement

#852 Dynamic tags in the first run
  GTG/core/firstrun_tasks.py
Labels: bug, enhancement
