Repository getting-things-gnome/gtg, pull requests merged in 2024-11, with the labels that each got.

#1150 Type fixes for versioning.py
  GTG/core/versioning.py
Labels: maintainability

#1151 Prevent reparenting a tag to itself
  GTG/gtk/browser/sidebar.py
Labels: bug

#1145 Remove liblarch
  .github/workflows/unit_tests.yml
  GTG/core/system_info.py
  GTG/gtk/browser/main_window.py
  GTG/gtk/tag_completion.py
  README.md
  build-aux/python3-requirements.yaml
  build-aux/requirements.txt
  snap/snapcraft.yaml
Labels: documentation, dependencies

#1156 Minor type fixes for core
  GTG/backends/generic_backend.py
  GTG/core/info.pyi
  GTG/core/plugins/engine.py
  GTG/core/search.py
  GTG/core/sorters.py
Labels: maintainability

#1152 Ensure consistent indentation when displaying trees
  GTG/gtk/data/style.css
Labels: enhancement
