Repository getting-things-gnome/gtg, pull requests merged in 2024-03, with the labels that each got.

#1037 Append short commit hash in development profile
  GTG/core/meson.build
Labels: packaging, maintainability

#1062 Prevent parsing the current word as a tag when editing a task
  GTG/gtk/editor/editor.py
  GTG/gtk/editor/taskview.py
Labels: bug, priority:high

#981 Properly maintain the task count in Tag.set_parent (fix #404)
  GTG/core/datastore.py
  GTG/core/tags.py
  GTG/gtk/browser/sidebar.py
Labels: bug

#943 Added strftime to Date
  GTG/core/dates.py
Labels: bug

#946 Fixed missing build dependancy for Fedora
  README.md
Labels: packaging, documentation

#1076 Avoid deleting an unedited new task twice
  GTG/gtk/editor/editor.py
Labels: bug

#953 readme: Remove outdated and obsolete build status badge
  README.md
Labels: maintainability
