Repository getting-things-gnome/gtg, pull requests merged in 2024-07, with the labels that each got.

#1119 Fix re-opening task editors
  GTG/gtk/browser/main_window.py
Labels: bug

#1120 Simple typing fixes for tasks.py
  GTG/core/tasks.py
Labels: enhancement, maintainability

#1122 Use GNOME 46 in weekly flatpak
  .github/workflows/weekly_flatpak.yml
  build-aux/org.gnome.GTG.Devel.json
Labels: packaging

#1125 chore: move snap to core24 and GNOME 46
  .gitignore
  snap/snapcraft.yaml
Labels: packaging

#1126 Fixes for 'filter_tag'
  GTG/core/tags.py
  GTG/core/tasks.py
Labels: bug

#1121 Fix hamster activation
  GTG/plugins/hamster/hamster.py
Labels: bug

#1124 More Ruff fixes
  GTG/core/base_store.py
  GTG/core/clipboard.py
  GTG/core/config.py
  GTG/core/tags.py
  GTG/core/tasks.py
  GTG/gtk/backends/parameters_ui/__init__.py
  GTG/gtk/browser/adaptive_button.py
  GTG/gtk/browser/main_window.py
  GTG/gtk/browser/task_pane.py
  GTG/gtk/colors.py
  GTG/gtk/editor/calendar.py
  GTG/gtk/editor/recurring_menu.py
  GTG/gtk/errorhandler.py
  GTG/plugins/gamify/gamify.py
  GTG/plugins/unmaintained/tomboy/tomboy.py
  scripts/anonymize_task_file.py
  tests/core/test_quickadd.py
  tests/core/test_saved_search.py
  tests/core/test_tag_store.py
  tests/core/test_task.py
  tests/core/test_taskview.py
Labels: maintainability

#1123 Add queue of ExceptionHandlerDialogs
  GTG/gtk/browser/main_window.py
  GTG/gtk/browser/task_pane.py
  GTG/gtk/errorhandler.py
Labels: bug, enhancement
