Repository getting-things-gnome/gtg, pull requests merged in 2024-12, with the labels that each got.

#1157 Fix focusing on new sidebar
  GTG/gtk/browser/main_window.py
Labels: bug

#1160 Create keyboard shortcuts to switch between Open, Actionable and Closed issue#975
  GTG/gtk/browser/main_window.py
Labels: enhancement

#1162 Remove old List use introduced by another branch from base_store.py
  GTG/core/base_store.py
Labels: bug, priority:critical, regression

#1165 Tests and related bugfixes for BaseStore.remove
  GTG/core/base_store.py
  GTG/core/saved_searches.py
  tests/core/test_base_store.py
Labels: bug, enhancement

#1166 Tests and a fix for BaseStore.parent
  GTG/core/base_store.py
  tests/core/test_base_store.py
Labels: bug, enhancement, maintainability
