Repository getting-things-gnome/gtg, pull requests merged in 2024-08, with the labels that each got.

#1132 Fix (almost) every typing error in saved_searches.py
  GTG/core/saved_searches.py
  tests/core/test_saved_search.py
Labels: enhancement, maintainability

#1131 Fix sidebar updates for tags
  GTG/core/tags.py
Labels: bug, enhancement

#1127 Look for parent in due date binding
  GTG/core/tasks.py
Labels: bug
