Repository getting-things-gnome/gtg, pull requests merged in 2024-04, with the labels that each got.

#1084 Fix deprecation warning
  GTG/core/tasks.py
Labels: enhancement, maintainability

#1030 Show parent's title & children count in "Open Parent" button tooltip
  GTG/gtk/editor/editor.py
Labels: enhancement

#1090 Remove tests from checks
  Makefile
Labels: bug, maintainability

#1065 Add simple pre-commit hook
  .github/workflows/unit_tests.yml
  .pre-commit-config.yaml
  README.md
Labels: maintainability

#1094 Update models for subtasks upon changes
  GTG/core/tasks.py
  GTG/gtk/browser/task_pane.py
Labels: bug, enhancement

#1091 Fix RMB menu for first task
  GTG/gtk/browser/task_pane.py
Labels: bug

#1088 Restore the selected pane saved in config
  GTG/gtk/browser/main_window.py
Labels: bug

#986 Fix an inappropriate test expression to remove a logical short circuit
  GTG/gtk/browser/main_window.py
Labels: maintainability
