Repository getting-things-gnome/gtg, pull requests merged in 2024-05, with the labels that each got.

#1095 Create a dummy button in the sidebar
  GTG/gtk/browser/sidebar.py
  GTG/gtk/data/style.css
Labels: bug, enhancement

#1098 Fix tag expansion in TaskPaneFilter
  GTG/core/filters.py
Labels: bug, enhancement

#1099 Fix the collection of parents in TagStore's XML export
  GTG/core/tags.py
Labels: bug, enhancement

#1100 Always show tags with zero tasks
  GTG/core/filters.py
  GTG/gtk/browser/sidebar.py
Labels: bug, enhancement

#1087 Save sort setting in config
  GTG/core/config.py
  GTG/gtk/browser/main_window.py
Labels: enhancement

#1096 Fix appdata related issues
  data/org.gnome.GTG.appdata.xml.in.in
Labels: enhancement, packaging

#1101 Inherit the parent's tags when creating a new subtask
  GTG/core/tasks.py
Labels: bug

#1102 Fix the mixed-use of UUID and str for task IDs
  GTG/core/base_store.py
  GTG/core/tasks.py
  GTG/gtk/editor/taskview.py
  tests/core/test_task.py
Labels: bug

#1105 Apply simple Ruff fixes
  GTG/backends/generic_backend.py
  GTG/core/base_store.py
  GTG/core/config.py
  GTG/core/filters.py
  GTG/core/sorters.py
  GTG/core/system_info.py
  GTG/core/versioning.py
  GTG/gtk/application.py
  GTG/gtk/backends/backendstree.py
  GTG/gtk/browser/delete_task.py
  GTG/gtk/browser/main_window.py
  GTG/gtk/browser/search_editor.py
  GTG/gtk/browser/sidebar_context_menu.py
  GTG/gtk/browser/tag_editor.py
  GTG/gtk/colors.py
  GTG/gtk/editor/calendar.py
  GTG/gtk/editor/editor.py
  GTG/gtk/errorhandler.py
  GTG/gtk/general_preferences.py
  GTG/gtk/plugins.py
  GTG/plugins/export/templates.py
  GTG/plugins/gamify/gamify.py
  GTG/plugins/send_email/sendEmail.py
  GTG/plugins/unmaintained/bugzilla/bugzilla.py
  tests/core/test_tag_store.py
  tests/core/test_task.py
  tests/tools/test_tags.py
Labels: enhancement, maintainability
