Repository getting-things-gnome/gtg, pull requests merged in 2024-06, with the labels that each got.

#1117 Fix (almost) every type hint in tags.py
  GTG/core/tags.py
  GTG/core/tasks.py
  tests/core/test_tag_store.py
Labels: enhancement, maintainability

#1106 Add action to dismiss search bar
  GTG/gtk/browser/main_window.py
Labels: bug, enhancement

#1112 Refresh all views when day changes
  GTG/gtk/browser/main_window.py
Labels: bug

#1113 Unset searches when unselecting saved searches
  GTG/gtk/browser/sidebar.py
Labels: bug

#1083 Write unit test for TaskView.get_title()
  .github/workflows/unit_tests.yml
  GTG/core/tasks.py
  GTG/gtk/editor/editor.py
  GTG/gtk/editor/taskview.py
  tests/core/test_task.py
  tests/core/test_taskview.py
Labels: maintainability
