Repository getting-things-gnome/gtg, pull requests merged in 2024-09, with the labels that each got.

#1129 Improve version name
  GTG/core/meson.build
  build-aux/org.gnome.GTG.Devel.json
  data/org.gnome.GTG.appdata.xml.in.in
  meson.build
  meson_options.txt
Labels: packaging

#1136 Fix calendar selection for repeating tasks
  GTG/gtk/data/recurring_menu.ui
  GTG/gtk/editor/recurring_menu.py
Labels: bug

#1143 Remove whitespace to please pre-commit
  GTG/gtk/browser/main_window.py
Labels: bug

#1146 Suppress mismatched signature errors in type-checking
  GTG/core/base_store.py
  GTG/core/saved_searches.py
  GTG/core/tags.py
  GTG/core/tasks.py
Labels: enhancement, maintainability
