Repository getting-things-gnome/gtg, pull requests merged in 2025-06, with the labels that each got.

#1212 Ensure that colouring fills the entire row in the task list
  GTG/gtk/browser/task_pane.py
  GTG/gtk/data/style.css
Labels: bug

#1214 Notify change in row css when detagging
  GTG/core/tasks.py
Labels: bug

#1219 Speed up (and fix) TagCompletion initialisation
  GTG/gtk/tag_completion.py
Labels: bug, performance

#1221 Fix automatic unit tests
  .github/workflows/unit_tests.yml
Labels: maintainability
