Repository getting-things-gnome/gtg, pull requests merged in 2025-01, with the labels that each got.

#1168 Remember unselecting tags + disable saved search auto-selection
  GTG/gtk/browser/sidebar.py
Labels: bug

#1171 Test and refactor BaseStore.unparent
  GTG/core/base_store.py
  GTG/core/tags.py
  GTG/core/tasks.py
  GTG/gtk/browser/main_window.py
  GTG/gtk/browser/sidebar.py
  GTG/gtk/browser/task_pane.py
  GTG/gtk/editor/editor.py
  tests/core/test_base_store.py
  tests/core/test_task.py
Labels: enhancement, maintainability

#1174 Update links to old wiki
  GTG/core/firstrun_tasks.py
  GTG/core/info.py.in
  NEWS
  README.md
  docs/contributors/git workflow tips.md
  docs/contributors/release process and checklist.md
  docs/contributors/translating.md
  docs/source/releases/v0.3.1.rst
  tests/core/test_urlregex.py
Labels: documentation

#1173 Fix GTK version numbering in system_info.py
  GTG/core/system_info.py
Labels: bug
