Repository getting-things-gnome/gtg, pull requests merged in 2025-05, with the labels that each got.

#1205 Fix automatic unit test dependencies
  .github/workflows/unit_tests.yml
Labels: maintainability

#1209 Remove deleted saved searches from the UI
  GTG/core/saved_searches.py
Labels: bug

#1211 Disable edit button when multiple tags are selected
  GTG/gtk/browser/sidebar.py
  GTG/gtk/browser/sidebar_context_menu.py
Labels: bug, enhancement
